### ISSUE TITLE
python plot-roh.py error

### ISSUE THREAD

**Issue by zuodabin** [samtools/bcftools#1723]
Hi ,the error masseage is No data files found in "F101.out.gz" ,can you tell me how to fix it？Thinks !
my data :
# This file was produced by: bcftools roh(1.12+htslib-1.12)
# The command line was:	bcftools roh -G30 --AF-dflt 0.4 F101.filter.vcf
#
# RG	[2]Sample	[3]Chromosome	[4]Start	[5]End	[6]Length (bp)	[7]Number of markers	[8]Quality (average fwd-bwd phred score)
# ST	[2]Sample	[3]Chromosome	[4]Position	[5]State (0:HW, 1:AZ)	[6]Quality (fwd-bwd phred score)
ST	F101	chr1	2497784	1	3.0
ST	F101	chr1	2497789	1	41.2
ST	F101	chr1	2497797	1	41.2
ST	F101	chr1	2497800	1	41.2
ST	F101	chr1	2497884	1	41.2
ST	F101	chr1	2593843	1	41.2

**Comment by pd3** [comment]
The script takes a directory with roh output files on input, but it seems you provided a file name rather than a directory?

**Comment by thedam** [comment]
In the input dir should be outputs from 'bcftools roh' written as .txt.gz (I found it in the plot-roh.py code) 
However still I have an error.
My input dir looks like that:
```
ls inputs/
roh1.txt.gz  roh2.txt.gz  roh3.txt.gz
```
then I run `plot-roh.py inputs` and get error

```
plot-roh.py inputs
/usr/local/bin/plot-roh.py:432: UserWarning: Attempting to set identical left == right == 0 results in singular transformations; automatically expanding.
  ax1.set_xlim(min_x,max_x+xlim*max_x)
Traceback (most recent call last):
  File "/home/damian/anaconda3/envs/aimed4/lib/python3.9/site-packages/PIL/ImageFile.py", line 506, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/plot-roh.py", line 450, in <module>
    plt.savefig(file,dpi=dpi)
  File "/home/damian/anaconda3/envs/aimed4/lib/python3.9/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/damian/anaconda3/envs/aimed4/lib/python3.9/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/damian/anaconda3/envs/aimed4/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/home/damian/anaconda3/envs/aimed4/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/damian/anaconda3/envs/aimed4/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 510, in print_png
    mpl.image.imsave(
  File "/home/damian/anaconda3/envs/aimed4/lib/python3.9/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/damian/anaconda3/envs/aimed4/lib/python3.9/site-packages/PIL/Image.py", line 2158, in save
    save_handler(self, fp, filename)
  File "/home/damian/anaconda3/envs/aimed4/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 1284, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/home/damian/anaconda3/envs/aimed4/lib/python3.9/site-packages/PIL/ImageFile.py", line 514, in _save
    e.setimage(im.im, b)
SystemError: tile cannot extend outside image
```


ps. where can I find any documentation so I could fully understand the output of "bcftools roh"??

my input files:
[roh3.txt.gz](https://github.com/samtools/bcftools/files/9505291/roh3.txt.gz)
[roh2.txt.gz](https://github.com/samtools/bcftools/files/9505294/roh2.txt.gz)
[roh1.txt.gz](https://github.com/samtools/bcftools/files/9505295/roh1.txt.gz)

**Comment by thedam** [comment]
So STs with state 1 are collapsed into RG... and I should look only for RG.
In plot-roh.py there is also condition for GT `if row[0]=='GT'`:, but I guess it is something else...

Anyway, I'll make a new issue with this plot-roh.py
Thanks
