### ISSUE TITLE
bcftools norm crash

### ISSUE THREAD

**Issue by jkbonfield** [samtools/bcftools#385]
I have some simulated data from editing chr20 which happens to have an indel into the telomere N region:

```
##fileformat=VCFv4.2
##contig=<ID=20,length=99999>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
20	17664	.	NN	N	.	.	.
```

This causes bcftools to explode:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7236567 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) where
#0  0x00007ffff7236567 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000000444354 in realign (args=0x755010, line=0x796910) at vcfnorm.c:354
#2  0x000000000044fa7c in normalize_line (args=0x755010, line_ptr=0x796730) at vcfnorm.c:1547
#3  0x0000000000450196 in normalize_vcf (args=0x755010) at vcfnorm.c:1634
#4  0x0000000000450e06 in main_vcfnorm (argc=4, argv=0x7fffffffdc10) at vcfnorm.c:1800
#5  0x000000000040d5ee in main (argc=5, argv=0x7fffffffdc08) at main.c:262
(gdb) up
#1  0x0000000000444354 in realign (args=0x755010, line=0x796910) at vcfnorm.c:354
354	            memmove(als[i].s,als[i].s+ntrim_left,als[i].l-ntrim_left);
(gdb) p als[i].l-ntrim_left
$4 = 18446744073709551517
(gdb) p als[i]
$2 = {
  l = 1, 
  m = 128, 
  s = 0x797020 "N"
}
(gdb) p ntrim_left
$3 = 100
```

**Comment by pd3** [comment]
This is now fixed, thanks for the test case.

**Comment by jkbonfield** [comment]
Thanks Petr.
