### ISSUE TITLE
bcftools csq: Segmentation fault

### ISSUE THREAD

**Issue by janinl** [samtools/bcftools#533]
Hello,

I unfortunately seem to have found a bug in `bcftools csq` when using this variant:
```
15	22472907	.	CCCTCACTGTGTCTCTCGCACAGTAATACACGGCCCTGT	C	603	PASS	DP=110748	GT:GQ:DP:DPF:AD:PF	0/0:100:79:.:.:.
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004af5bc in sanity_check_ref (args=0x78b010, tr=0xe06f40, rec=0x6d08c20) at csq.c:3092
3092	    while ( *ref && *alt )

3090	    char *ref = tr->ref + (rec->pos - tr->beg + N_REF_PAD);
(gdb) p rec->pos
$1 = 22472906
(gdb) p tr->beg
$2 = 22472917
(gdb) p rec->pos - tr->beg + 10
$3 = 4294967295
(gdb) p tr->ref
$5 = 0x6d04920 "CCTCACTGTGTCTCTCGCACAGTAATACACGGCCCTGTCCGCGGCGGTCACAGAGCTCAGCTTCAGGGAGAACTGGTTCTTGGACTTGTCTACTGATATGGTGACTCGACTCTTGAGGGACGGGTTGTAGTTGGGGCTCCCACTATGATAGATTTCCCCAATCCACTCCAGCCCCTTCCCTGGGGGCTGGCGGACCCAGC"...
(gdb) p ref
$4 = 0x106d0491f <error: Cannot access memory at address 0x106d0491f>
(gdb) backtrace
#0  0x00000000004af5bc in sanity_check_ref (args=0x78b010, tr=0xe06f40, rec=0x6d08c20) at csq.c:3092
#1  0x00000000004b0433 in test_cds (args=0x78b010, rec=0x6d08c20) at csq.c:3298
#2  0x00000000004b1f10 in process (args=0x78b010, rec_ptr=0x6d083e0) at csq.c:3616
#3  0x00000000004b253c in main_csq (argc=6, argv=0x7fffffffe520) at csq.c:3773
#4  0x000000000040f2e1 in main (argc=7, argv=0x7fffffffe518) at main.c:267
```

The reference block `tr->ref` seems to start one base too far, which makes the `ref` pointer point one byte before this array.

To reproduce the problem, here are the (small) files I used:
**15.vcf**
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##INFO=<ID=DP,Number=1,Type=Integer,Description="sum of depth  across all samples">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Filtered basecall depth used for site genotyping">
##FORMAT=<ID=DPF,Number=1,Type=Integer,Description="Basecalls filtered from input prior to site genotyping">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed.">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=PF,Number=A,Type=Integer,Description="variant was PASS filter in original sample gvcf">
##contig=<ID=15,length=102531392>
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	05C42000-final
15	22472907	.	CCCTCACTGTGTCTCTCGCACAGTAATACACGGCCCTGT	C	603	PASS	DP=110748	GT:GQ:DP:DPF:AD:PF	0/0:100:79:.:.:.
```

Other files from:
```
ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz
http://ftp.ensembl.org/pub/grch37/release-82/gff3/homo_sapiens/Homo_sapiens.GRCh37.82.chr.gff3.gz
```

**Command:**
```
bcftools csq -f hs37d5.fa -g Homo_sapiens.GRCh37.82.chr.gff3.gz 15.vcf
```

(checked this morning with latest htslib&bcftools from develop branch)

Kind regards
Lilian

**Comment by pd3** [comment]
Thank you for the debugging output and the test case! The bug is now fixed.

**Comment by janinl** [comment]
Thanks a lot! So efficient!
