### ISSUE TITLE
csq: double free error

### ISSUE THREAD

**Issue by brentp** [samtools/bcftools#584]
version:
```
bcftools 1.4-7-g41827a3
Using htslib 1.4-7-g9986f5d
```

invocation:
```
bcftools csq --local-csq -p R -g ./Homo_sapiens.GRCh37.82.gff3.gz -f /data/human/g1k_v37_decoy.fa $vcf
```

here's the backtrace from GDB:
```
Program received signal SIGABRT, Aborted.
0x00007ffff6ccd428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace 
#0  0x00007ffff6ccd428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6ccf02a in __GI_abort () at abort.c:89
#2  0x00007ffff6d0f7ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff6e282e0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6d17e0a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, 
    str=0x7ffff6e28410 "double free or corruption (!prev)", action=3) at malloc.c:5004
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3865
#5  0x00007ffff6d1b98c in __GI___libc_free (mem=<optimized out>) at malloc.c:2966
#6  0x000000000048445a in vbuf_flush (args=args@entry=0x761010) at csq.c:3075
#7  0x000000000048af50 in vbuf_flush (args=0x761010) at csq.c:3632
#8  process (args=args@entry=0x761010, rec_ptr=0x6d24320) at csq.c:3627
#9  0x000000000048b3a4 in main_csq (argc=<optimized out>, argv=<optimized out>) at csq.c:3789
#10 0x00007ffff6cb8830 in __libc_start_main (main=0x40f850 <main>, argc=10, argv=0x7fffffffdc98, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdc88) at ../csu/libc-start.c:291
#11 0x000000000040fa89 in _start ()
```

**Comment by pd3** [comment]
Thank you for the bug report. Any chance you could create a small test case to reproduce the error?

**Comment by brentp** [comment]
See attached. 
[u.vcf.gz](https://github.com/samtools/bcftools/files/894150/u.vcf.gz)

**Comment by pd3** [comment]
Thanks for the test case, it's fixed now.

**Comment by brentp** [comment]
thank you.
