### ISSUE TITLE
Plotting issue vcf-plot

### ISSUE THREAD

**Issue by aderzelle** [samtools/bcftools#719]
Hello,
I can't plot the output of bcftools stats. 

```
bcftools stats -F contigs.fa -s - filtered_samtools.vcf.gz > filtered_samtools.vcf.gz.stats
plot-vcfstats -p samtools_plot filtered_samtools.vcf.gz.stats
```

I am on manjaro linux executing bcftools version 1.6 

Here is the error 

```
Parsing bcftools stats output: filtered_samtools.vcf.gz.stats
Warning: Possible version mismatch, the definition line differs
        expected: # PSC [2]id   [3]sample       [4]nRefHom      [5]nNonRefHom   [6]nHets        [7]nTransitions [8]nTransversions       [9]nIndels      [10]average depth       [11]nSingletons
        found:    # PSC [2]id   [3]sample       [4]nRefHom      [5]nNonRefHom   [6]nHets        [7]nTransitions [8]nTransversions       [9]nIndels      [10]average depth       [11]nSingletons [12]nHapRef     [13]nHapAlt
Plotting graphs: python plot.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2570, in ticklabel_format
    self.yaxis.major.formatter.set_scientific(sb)
AttributeError: 'StrCategoryFormatter' object has no attribute 'set_scientific'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "plot.py", line 283, in <module>
    ax1.ticklabel_format(style='sci', scilimits=(0,0), axis='y')
  File "/usr/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2593, in ticklabel_format
    "This method only works with the ScalarFormatter.")
AttributeError: This method only works with the ScalarFormatter.
The command exited with non-zero status 256:
        python plot.py

 at /usr/local/bin/plot-vcfstats line 95.
        main::error("The command exited with non-zero status 256:\x{a}\x{9}python plot.py\x{a}\x{a}") called at /usr/local/bin/plot-vcfstats line 283
        main::plot(HASH(0x559f71c06fb0)) called at /usr/local/bin/plot-vcfstats line 65
```

Any idea? thanks

**Comment by pd3** [comment]
It looks like a matpltolib version issue. Can you check what version of matplotlib are you running?
````
>>> import matplotlib
>>> matplotlib.__version__
'1.4.3'
````

Also seeing the output of the `stats` command would be helpful.

**Comment by aderzelle** [comment]
It's version 2.1.0

Here is the beginning of the stats

```
# This file was produced by bcftools stats (1.6+htslib-1.6) and can be plotted using plot-vcfstats.
# The command line was:	bcftools stats  -F contigs.fa -s - filtered_samtools.vcf.gz
#
# Definition of sets:
# ID	[2]id	[3]tab-separated file names
ID	0	filtered_samtools.vcf.gz
# SN, Summary numbers:
#   number of records   .. number of data rows in the VCF
#   number of no-ALTs   .. reference-only sites, ALT is either "." or identical to REF
#   number of SNPs      .. number of rows with a SNP
#   number of MNPs      .. number of rows with a MNP, such as CC>TT
#   number of indels    .. number of rows with an indel
#   number of others    .. number of rows with other type, for example a symbolic allele or
#                          a complex substitution, such as ACT>TCGA
#   number of multiallelic sites     .. number of rows with multiple alternate alleles
#   number of multiallelic SNP sites .. number of rows with multiple alternate alleles, all SNPs
# 
#   Note that rows containing multiple types will be counted multiple times, in each
#   counter. For example, a row with a SNP and an indel increments both the SNP and
#   the indel counter.
# 
# SN	[2]id	[3]key	[4]value
SN	0	number of samples:	1
SN	0	number of records:	8383
SN	0	number of no-ALTs:	0
SN	0	number of SNPs:	7964
SN	0	number of MNPs:	0
SN	0	number of indels:	419
SN	0	number of others:	0
SN	0	number of multiallelic sites:	7
SN	0	number of multiallelic SNP sites:	5
# TSTV, transitions/transversions:
# TSTV	[2]id	[3]ts	[4]tv	[5]ts/tv	[6]ts (1st ALT)	[7]tv (1st ALT)	[8]ts/tv (1st ALT)
TSTV	0	4784	3185	1.50	4783	3181	1.50
# ICS, Indel context summary:
# ICS	[2]id	[3]repeat-consistent	[4]repeat-inconsistent	[5]not applicable	[6]c/(c+i) ratio
ICS	0	170	7	244	0.9605
# ICL, Indel context by length:
# ICL	[2]id	[3]length of repeat element	[4]repeat-consistent deletions)	[5]repeat-inconsistent deletions	[6]consistent insertions	[7]inconsistent insertions	[8]c/(c+i) ratio
ICL	0	2	45	1	34	1	0.9753
ICL	0	3	33	1	33	0	0.9851
ICL	0	4	5	0	3	1	0.8889
ICL	0	5	3	0	1	0	1.0000
ICL	0	6	4	0	1	3	0.6250
ICL	0	7	0	0	0	0	0.0000
ICL	0	8	1	0	0	0	1.0000
ICL	0	9	6	0	1	0	1.0000
ICL	0	10	0	0	0	0	0.0000
# SiS, Singleton stats:
# SiS	[2]id	[3]allele count	[4]number of SNPs	[5]number of transitions	[6]number of transversions	[7]number of indels	[8]repeat-consistent	[9]repeat-inconsistent	[10]not applicable
SiS	0	1	5039	2961	2078	324	140	5	179
# AF, Stats by non-reference allele frequency:
# AF	[2]id	[3]allele frequency	[4]number of SNPs	[5]number of transitions	[6]number of transversions	[7]number of indels	[8]repeat-consistent	[9]repeat-inconsistent	[10]not applicable
AF	0	0.000000	5039	2961	2078	324	140	5	179
AF	0	0.990000	2930	1823	1107	97	30	2	65
# QUAL, Stats by quality:
# QUAL	[2]id	[3]Quality	[4]number of SNPs	[5]number of transitions (1st ALT)	[6]number of transversions (1st ALT)	[7]number of indels
QUAL	0	10	163	104	59	17
QUAL	0	11	136	75	61	17
QUAL	0	12	105	60	45	12
QUAL	0	13	143	87	56	6
QUAL	0	14	133	90	43	8
QUAL	0	15	123	79	44	11
QUAL	0	16	119	77	42	7
QUAL	0	17	102	57	45	11
QUAL	0	18	116	80	36	10
QUAL	0	19	145	84	61	4
QUAL	0	20	109	67	42	5
QUAL	0	21	86	54	32	5
QUAL	0	22	152	97	55	6
```

Maybe it's better that I send the whole file?

**Comment by pd3** [comment]
yes, the whole file will be needed. My email is on my profile page, thank you

**Comment by pd3** [comment]
Thank you for the test case.

I attempted to test with the latest matplotlib release but run into other problems in the internals of matplotlib. My installation is probably broken, the code there fails in numpy's `stride_tricks.py` and I cannot even run some of the code examples. I am afraid debugging this is beyond the support I can provide right now.

However, a quick workaround is to comment out the offending lines in the `plot.py` script generated by `plot-vcfstats`. Your stats file has only one sample, most of the plots are not showing anything meaningful anyway.

**Comment by aderzelle** [comment]
Thanks but could you be slightly more specific? I did not understand which line I was supposed to comment out.

**Comment by pd3** [comment]
It's the scientific formatting, the error message suggests it's on line 283
````
 File "plot.py", line 283, in <module>
    ax1.ticklabel_format(style='sci', scilimits=(0,0), axis='y')
````

**Comment by aderzelle** [comment]
That works well, in fact I had to comment out all instances of this line
`ax1.ticklabel_format(style='sci', scilimits=(0,0), axis='y')
`
Thanks a lot
